CREATE TABLE IF NOT EXISTS IHOMECONFIG (
	fID 			INT 			NOT NULL		PRIMARY KEY,
	fName 			VARCHAR(20),
	fPassword		VARCHAR(20),
	fInnerIP 		VARCHAR(20)		NOT NULL,
	fOuterIP	 	VARCHAR(100)		NOT NULL
); 

INSERT OR IGNORE INTO IHOMECONFIG (fID, fName, fPassword, fInnerIP, fOuterIP) VALUES (1, NULL, NULL, '192.168.1.230', '192.168.1.230');
